### ISSUE TITLE
Version 3.0 instead of 3.1

### ISSUE THREAD

**Issue by Nachtfrische** [sbpp/donations-control-pp#1]
Hey,

I'm completly new to this extension so I apologize for any mistakes in advance.

I've just downloaded this fork and tried to set it up. It worked fine until I wanted to log in. It keeps telling me that I have the wrong password. After a quick google search I found out that there is a version of SB++ compatibility which adds salt to the passwords. 

So I looked at my config.php which I got from this fork and saw, that the file isn't having anything related to salts. Also, at the top of the config.php file, it says that it's Version 3.0.0 but as far as I know, the newest version is 3.1.0.

Is that why I can't log in as an admin?

Thanks.

**Comment by Groruk** [comment]
- This fork is based on the [original repo](https://bitbucket.org/brewskii187/donations-control) so it's version 3.1.0 ([3.1.2](https://github.com/sbpp/donations-control-pp/blob/master/web/donations/includes/version.php) to be specific).
- Salting in SourceBans++ (1.6.2+) and Donation-Control++ are done via php's [password_hash()](http://php.net/manual/en/function.password-hash.php) function, so there is no config option for salts.
- Login errors normally occur when the config is not correctly set up. Be sure that you have set a valid SourceBans++ group in your [config](https://github.com/sbpp/donations-control-pp/blob/master/web/donations/includes/config.php#L55) and that you have added the user to the group, else he wont have [permission to login](https://github.com/sbpp/donations-control-pp/blob/master/web/donations/admin/index.php#L18)

**Comment by Nachtfrische** [comment]
Thank you for your reply.
My group in SB++ is called "FullAdminSERVER", however, when I put that in the config, I still get the same error.

Do you have any thoughts on why that could happen?

**Comment by Groruk** [comment]
Make sure that your admin is also assigned to that specific `Server Admin Group`.

You can also remove the check for a group by removing `and srv_group = '" . SB_ADMINS . "'` from the [admin/index.php](https://github.com/sbpp/donations-control-pp/blob/master/web/donations/admin/index.php#L18)

**Comment by Nachtfrische** [comment]
Alright, thank you for your help 👍
